version: 2

models:
  - name: stg_local_bike_sales__orders
    description: "This model contains information about orders placed by customers, including the status of each order and shipment date."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: customer_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
            - not_null
          - relationships:
              arguments:
                to: ref('stg_local_bike_sales__customers')
                field: user_id
      - name: order_status
        description: "The current status of the order."
        tests:
            - not_null
          - accepted_values:
              arguments: 
                values: ['1', '2', '3', '4']
      - name: order_date
        description: "The date the order was placed."
        tests:
            - not_null
      - name: required_date
        description: "The date the customer wants the delivery."
        tests:
            - not_null
      - name: store_id
        description: "Foreign key linking the order to the corresponding store."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike_sales__stores')
                field: store_id
      - name: staff_id
        description: "Foreign key linking the order to the corresponding staff."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike_sales__staffs')
                field: order_id

  - name: stg_local_bike_sales__order_items
    description: "This model contains information about each item included in an order, including its price, quantity, and shipping cost."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike_sales__orders')
                field: order_id
      - name: total_order_item_amount
        description: "The total amount for this order item, calculated as (price * quantity) + shipping_cost."

  - name: stg_local_bike_sales__staffs
    description: "This model contains information about payments made for orders, including the sequential payment number."
    columns:
      - name: payment_id
        description: "Primary key, unique identifier for each payment: generated by concatenating order_id and payment_sequential."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the payment to the corresponding order."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike_sales__orders')
                field: order_id


  - name: stg_local_bike_sales__stores
    description: "This model contains information about the sellers who provide the products."
    columns:
      - name: seller_id
        description: "Primary key, unique identifier for each seller."
        tests:
            - unique
            - not_null

  - name: stg_local_bike_sales__customers
    description: "This model contains user-related information, including where they live."
    columns:
      - name: user_id
        description: "Primary key, unique identifier for each user."
        tests:
            - unique
            - not_null



